package com.model;
// Generated 08-Apr-2022, 8:53:49 pm by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand implements java.io.Serializable {

	private Integer brandId;
	private String brandTitle;
	private String brandDescription;
	private Set products = new HashSet(0);

	public Brand() {
	}

	public Brand(String brandTitle, String brandDescription, Set products) {
		this.brandTitle = brandTitle;
		this.brandDescription = brandDescription;
		this.products = products;
	}

	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	public String getBrandTitle() {
		return this.brandTitle;
	}

	public void setBrandTitle(String brandTitle) {
		this.brandTitle = brandTitle;
	}

	public String getBrandDescription() {
		return this.brandDescription;
	}

	public void setBrandDescription(String brandDescription) {
		this.brandDescription = brandDescription;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
