package com.model;
// Generated 08-Apr-2022, 8:53:49 pm by Hibernate Tools 5.6.3.Final

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer cartId;
	private Product product;
	private Users users;
	private String size;
	private Integer quantity;
	private Integer price;

	public Cart() {
	}

	public Cart(Product product, Users users, String size, Integer quantity, Integer price) {
		this.product = product;
		this.users = users;
		this.size = size;
		this.quantity = quantity;
		this.price = price;
	}

	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

}
