package com.model;
// Generated 08-Apr-2022, 8:53:49 pm by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cloth generated by hbm2java
 */
public class Cloth implements java.io.Serializable {

	private int clothId;
	private String clothTitle;
	private String clothDescription;
	private Set products = new HashSet(0);

	public Cloth() {
	}

	public Cloth(int clothId) {
		this.clothId = clothId;
	}

	public Cloth(int clothId, String clothTitle, String clothDescription, Set products) {
		this.clothId = clothId;
		this.clothTitle = clothTitle;
		this.clothDescription = clothDescription;
		this.products = products;
	}

	public int getClothId() {
		return this.clothId;
	}

	public void setClothId(int clothId) {
		this.clothId = clothId;
	}

	public String getClothTitle() {
		return this.clothTitle;
	}

	public void setClothTitle(String clothTitle) {
		this.clothTitle = clothTitle;
	}

	public String getClothDescription() {
		return this.clothDescription;
	}

	public void setClothDescription(String clothDescription) {
		this.clothDescription = clothDescription;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
